#this is the makefile of EpollTest  
.PHONY:all  
all:EpollServer EpollClient  
server:  
	g++ EpollServer.cpp -o EpollServer  
client:  
	gcc EpollClient.cpp -o EpollClient  
clean:  
	rm -f EpollServer EpollClient  
